name-template: 'v$NEXT_MAJOR_VERSION'
tag-template: 'v$NEXT_MAJOR_VERSION'
version-template: '3.11.0-bearingpoint-$MAJOR'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '* $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES